clear; close all; clc
g = @(x) sin(exp(2*x));
f = @(x) sin(x);
a = 0;
b = 2;
tol = 10.^-3;
Ie = integral(g,a,b);
pts =[a,b];
[Ia,nint, x] = IntAdapt(g,a,b,tol,1, pts);
%[Ia, x] = Test(g,a,b,tol,pts);
x = sort(x);
x = unique(x);
y = g(x);
x1 = linspace(0,2,500);
y1 = g(x1);
plot(x,0,'or');
hold on;
plot(x1,y1,'-b');
hold on;
plot(x,y,'k*');
